### ISSUE TITLE
OSX support?

### ISSUE THREAD

**Issue by BHamrick1** [OfficeDev/skype-ios-app-sdk-samples#12]
We have a framework similar to iOS running on OSX. We would love to use this framework but it seems like it is built without the x86 build flag. Could this be possible in the future?

**Comment by richardtaylorrt** [comment]
Hi - yes, we are considering a Mac version of the App SDK in future but we have no immediate plans for this.  (Note there is an x86 version of the framework included in the SDK download, but this is only for running on the iOS simulator.  Producing a Mac version of the SDK will unfortunately require a lot more than just building for x86!)
