### ISSUE TITLE
SDK not running on ios 9.3

### ISSUE THREAD

**Issue by libinmjacob** [OfficeDev/skype-ios-app-sdk-samples#13]
I have tried running the sample application on ios 9.3 (iphone 6) and it gives the following error

"dyld: Library not loaded: @rpath/SkypeForBusiness.framework/SkypeForBusiness"

**Comment by richardtaylorrt** [comment]
Hi - please could you give a bit more detail.  Which sample app?  Have you followed the steps in its readme such as [this one](https://github.com/OfficeDev/skype-ios-app-sdk-samples/blob/master/BankingAppObjectiveC/readme.md)?  What step does it go wrong?  Note there is a different .framework for running on a device vs running on the simulator.   Thanks.

**Comment by EnkiChen** [comment]
I've had the same problem，project for BankingAppObjectiveC

SDK version：App SDK for iOS – 0.5 (Preview)  downloan url：https://www.microsoft.com/en-us/download/details.aspx?id=51962
samples code：https://github.com/OfficeDev/skype-ios-app-sdk-samples  master branch
 
My current environment is：
XCode ： Version 7.3.1 (7D1014)
iOS SDK： iOS 9.3
Test equipment：Simulator for iPhone 6s iOS 9.3. For real iPhone 6 (iOS 9.3)

**Comment by EnkiChen** [comment]
Error prompt for：

dyld: Library not loaded: @rpath/SkypeForBusiness.framework/SkypeForBusiness
  Referenced from: /Users/Enki/Library/Developer/CoreSimulator/Devices/8A89A6F8-A8F4-47CF-9B09-B60661733609/data/Containers/Bundle/Application/28796954-B17B-4271-991B-2FE7FD7D3D49/BankingApp.app/BankingApp
  Reason: image not found

**Comment by AasveenKaur** [comment]
After you embed the framework, please clean the project before you run it. This might solve the problem.

**Comment by EnkiChen** [comment]
Thank you very much. I was so careless.

Add SkypeForBusiness.framework as an "Embedded Binary" (not a "Linked Framework").
