### ISSUE TITLE
Not able to initiate the skype meeting using BankingApp sample

### ISSUE THREAD

**Issue by msn-khan** [OfficeDev/skype-ios-app-sdk-samples#14]
I have followed all the steps and have configured the sample application Banking APP (Obj-C).
I have also created a meeting URL using skype for meeting web application.
But when I plug it into the sample app it says connecting to the agent all the time and do nothing. 
Please help me.

**Comment by richardtaylorrt** [comment]
Hi - have you followed this note in the readme?

Note: To test the app, you need to join the meeting as a "bank agent" yourself by using the Skype for Business application installed on your desktop or mobile device. Join the same meeting URL that you configured in the app above.

**Comment by msn-khan** [comment]
Yes, I created a meeting URL from Lync for MAC client, and copied the same URL in the plist, still it is not working.

**Comment by richardtaylorrt** [comment]
Hi - two other things to check:

- Is the meeting configured to allow guests to join immediately?  You may find the 'guest' is stuck in the meeting 'lobby' in Lync for Mac, awaiting admission to the meeting.
- Are you using wifi or a mobile data network?  By default, video is disabled when not on wifi.  There is configuration (in SfBConfigurationManager) to change this.

If it's still not working, please could you send device logs to mailto:skypedevinsiders@microsoft.com 

Thanks.

**Comment by msn-khan** [comment]
Please check this log file. I need your help in this. Please help me.
[BankAgent-ObjC-Log.txt](https://github.com/OfficeDev/skype-ios-app-sdk-samples/files/295283/BankAgent-ObjC-Log.txt)

**Comment by AasveenKaur** [comment]
To get error details. You can make few changes in VideoViewController. Conform it to SfBAlertDelegate. In JoinMeeting function, add following lines:

 SfBApplication *sfb = SfBApplication.sharedApplication;
  sfb.alertDelegate = self;

Then implement delegate method "didReceiveAlert". This may help you to get error details.

- (void)didReceiveAlert:(SfBAlert *)alert
{
    NSLog(@"%@",alert.error.localizedDescription);
    
}

To get conversation level alerts. You should set alertDelegate of SfBConversation instance to self.

**Comment by jovillas** [comment]
Closing this ticket since the last OP didn't followed up the last suggestion, I believe it fixed the issue.

If this is not the case, please reopen the ticket.
