### ISSUE TITLE
Not able to run the sample demo with new SDK and getting frequent error message in Old SDK

### ISSUE THREAD

**Issue by manish-1988** [OfficeDev/skype-ios-app-sdk-samples#21]
The operation couldn’t be completed. (SfBErrorDomain error 570621972.)
Error Domain=SfBErrorDomain Code=570621972 "(null)" UserInfo={SfBErrorSeverity=SfBErrorSeverityError, ErrorNumber=20, Layer=TransportLayer, Component=ServerCommunication}
I am receiving this error message. 

I am able to integrate the SDK in a new project but in a existing project the call never gets executed . 
Can I find a proper link of use of this SDK in a swift project and also I am not able to compile the new updated Banking App demo project provided with the new SDK. 
It does not have SFBConversationHelper classes just having ChatHandler classes in helper folder.

**Comment by AasveenKaur** [comment]
Hi Manish,

Please follow the [ReadMe](https://github.com/OfficeDev/skype-ios-app-sdk-samples/blob/master/BankingAppSwift/readme.md) file for Banking App sample. 

You need to add SFBConversationHelper classes to sample. Also, make sure that you provide a valid meetingUrl. You should be connected to WIFI to run these samples.

Please read following docs to understand the integration process.
-[GettingStarted](https://github.com/OfficeDev/skype-docs/blob/master/Skype/AppSDK/GettingStarted.md)
-[HowToJoinMeeting_iOS](https://github.com/OfficeDev/skype-docs/blob/master/Skype/AppSDK/HowToJoinMeeting_iOS.md)

**Comment by jovillas** [comment]
I think the question was answered as the OP didn't followed up. Closing this ticket.
