### ISSUE TITLE
BankingAppSwift(iOS) video chat Domain Error

### ISSUE THREAD

**Issue by 591700757** [OfficeDev/skype-ios-app-sdk-samples#30]
Hi,
I am trying BankingAppSwift sample with the meeting url my co-worker gave me.
Which is a gust meeting url.
The demo worked in text chat mode,but i found that i can not use video chat with this demo.
While i run "videoService.start" in  VideoViewController
i get this exception:
SfBErrorDomain error 570621957

My Device is iphone5s 
OSversion is 9.3.5
The meeting url i'm using worked perfect while i use pc browser.
And when i try video chat i can see the use list there in pc browser only can not see any video
in the demo.
I try hard to solve it myself but i don't have much server experience and i found it hard to locate the
SfBErrorDomain definition.Hope you can help me.
Many Thanks.

**Comment by AasveenKaur** [comment]
Please make sure that you have the latest Banking App Sample and SDK version. Please check if enable preview = true in the Banking sample.
 **sfb.configurationManager.enablePreviewFeatures = true**

**Comment by const86** [comment]
Please provide full logs. Grab sfbios.log file from the application container, or copy-paste from the Xcode debug window. Also, compare your case with #31, you may have the same problem.

**Comment by 591700757** [comment]
I replace the SDK and it works.
Thanks very much!
