### ISSUE TITLE
Fail to start video using sample Banking App

### ISSUE THREAD

**Issue by YZSheng** [OfficeDev/skype-ios-app-sdk-samples#31]
Hi, 

We are using the sample banking app provided in this repository (Objective-C version). We have successfully joined the meeting if we choose to use Instant Message. Whenever we choose Video, we can see that it's failing because the following error:

> INFO APPLICATION CUcmpAudioVideoModality.cpp:2824 CUcmpAudioModality::queryCapability on StartVoIP returns false because startAudioVideo link in communication and conversation are both empty.

> INFO APPLICATION CUcmpConversationsManager.cpp:8771 canStartVoIPAudioOnBehalfOfDelegator returns false because P2PAudio is disabled 

We are using Xcode 8.0 and iPhone 6S Plus running on iOS 9.2.

Please find the successful InstantMessage device log and failed Video call device log attached.

Can you please let us know what this issue is and how to resolve it?

Thank you.

[bankingApp_video_failed.txt](https://github.com/OfficeDev/skype-ios-app-sdk-samples/files/585605/bankingApp_video_failed.txt)
[bankingApp_im_successful.txt](https://github.com/OfficeDev/skype-ios-app-sdk-samples/files/585606/bankingApp_im_successful.txt)

**Comment by AasveenKaur** [comment]
Please make sure that you have the latest Banking App Sample and SDK version. Please check if enable preview feature is set to true in the Banking sample.
**sfb.configurationManager.enablePreviewFeatures = true**

**Comment by const86** [comment]
Indeed, you're using on-prem SfB server. To use audio and video you have to use the latest App SDK version 0.7.1 with `enablePreviewFeatures = true`. Or update the server to CU4 released a few days ago. Previous App SDK release 0.7.0 behaves bravely as if `enablePreviewFeatures = false`.
