### ISSUE TITLE
Cac buoc thuc hien mut xoai kho thu vi

### ISSUE THREAD

**Issue by daylambanhauvn** [OfficeDev/skype-ios-app-sdk-samples#33]
Mứt xoài chính là sự kết hợp với perfect giữa xoài và đường. Cùng với chúng mình  học cách thực hiện mứt xoài khô thu hút khiến đi tìm lý do vì sao người ta lại yêu mứt xoài khô đến vậy nha !!

**Thành phần bạn cần có làm mứt xoài khô**

- Một kí lô xoài xanh

- 500 g đường trắng

- 1,5 gam phèn chua

- Nước vôi trong

**Các công cụ làm mứt xoài khô**

- Chén to to, nhỏ vừa

- Dao, dĩa, muổng, thớt, rổ, …

- Nồi , chảo

- Lọ thuỷ tinh hay bình kín có nắp trùm

**Cách thực hiện mứt xoài khô**

Quy trình 1:

- Các bạn nên chọn dạng xoài xanh không quá ngọt, cũng không quá chua nha !!

- Làm sạch mủ xoài, gọt vỏ bên ngoài sạch và tách xoài thành từng lát dài, nhớ rằng hạn chế tách mỏng nhờ mứt sẽ bị nát đấy!

Quy trình 2:

- Kế đến, các bạn om xoài vừa tách cùng với nước vôi trong, ngâm tôm ước tính chừng Sáu đến Bãy giờ đồng hồ.

- Sau khi hổn hợp om, vớt xoài ra rửa lại cùng với nước lạnh đến sạch vôi. Cho vào rổ cho khô nước.

Quy trình 3:

- Đặt nồi lên trên cùng bếp để đun cho nóng phèn chua. Các bạn đun nóng phèn chua cùng với 2 lít nước.

- Khi nước vừa sôi, cho xoài vào cùng với thời điểm Năm đến MƯỜI 'p, vớt xoài ra xả lại cùng với nước lạnh và mục đích ráo trong rổ.

Quy trình 4:

- Trong một cái chén to to, bạn cho xoài vào đó và cho vào 1 ít đường trắng. Các bạn nên ngâm tôm khoảng chừng Tám h cho đường cát hấp thụ và tan hoàn toàn nhé !!

- Đun cho nóng hỗn hợp xoài và nước đường cát, khi hỗn hợp sôi sẽ ít lại lửa vừa, đảo xoài nhờ muổng gỗ thường xuyên nhưng phải thật nhẹ nhàng, như thế xoài sẽ không bị nát và xoài sẽ hấp thụ đường cát hơn đấy!

Quy trình 5

- Đun nóng đến khi đường cát ráo và bám hết vào xoài là mứt xoài đã kết thúc rồi đấy!

- Khiến cho mứt trở nên khô hơn các bạn cần thiết thêm vào ngăn lạnh ngăn mát hay đem đi phơi nắng đến lập tức đạt được độ khô mà các bạn cần nha!

- Mứt siêu thơm ngon hết sẩy luôn đó nhé !! :3

- Các bạn cũng có thể gói ghém đem đi tặng người thân cũng là one lựa chọn không tồi đâu đấy!

Ước mong bạn thực hiện tốt cùng với cách làm món mứt xoài khô cuống hút này nha !

>> Bạn có thể tham khảo thêm một số công thức làm bánh ngon khác tại đây nhé : **[http://lambanhtrungthu.org/hoc-lam-banh-nhat](http://lambanhtrungthu.org/hoc-lam-banh-nhat)**

**Comment by jovillas** [comment]
Thanks for this Mango jam recipe.
Unfortunately, I don't think we should be adding that much sugar to the SDK, will talk with the rest of the team about it. In the meantime I'm closing this issue.
