### ISSUE TITLE
Migrate BankingAppSwift to Swift 3

### ISSUE THREAD

**Issue by 4brunu** [OfficeDev/skype-ios-app-sdk-samples#34]
Could you please migrate the BankingAppSwift to Swift 3?

I downloaded the sample, but I could run it with Xcode 8.

Thanks

**Comment by bryzinski** [comment]
Please checkout https://github.com/OfficeDev/skype-ios-app-sdk-samples/pull/55

**Comment by 4brunu** [comment]
Thanks 👍

**Comment by jovillas** [comment]
The code has been migrated to Swift3 on master.
