### ISSUE TITLE
Error: SkypeForBusiness.h and SfBConversationHelper.h not found

### ISSUE THREAD

**Issue by nikunjazilen** [OfficeDev/skype-ios-app-sdk-samples#40]
Hi Team,

I tried run the BankingAppObjectiveC and BankingAppSwift demo but its give me the error like "SkypeForBusiness.h and SfBConversationHelper.h file not found". I want to integrate video chat with text messaging like Skype iOS provided. Can you please help me to solve out this issue? So I can go ahead and testing the demo.

Best Regards,
Nikunj Jadav

**Comment by 591700757** [comment]
According to document in the place where we download the demo project(https://github.com/OfficeDev/skype-ios-app-sdk-samples/tree/master/BankingAppSwift)
 you need to do a few thing before you can run this demo.One of them is to drag those two file into demo project from SDK.

**Comment by jovillas** [comment]
Were you able to copy the files form the SDK package?
