### ISSUE TITLE
ios energy impact is extremely high

### ISSUE THREAD

**Issue by 591700757** [OfficeDev/skype-ios-app-sdk-samples#41]
I only run :
        let sfb:SfBApplication? = SfBApplication.shared()
        
        if let sfb = sfb{
            sfb.configurationManager.enablePreviewFeatures = true
            sfb.configurationManager.maxVideoChannels = 1
            sfb.configurationManager.requireWifiForVideo = false
//            sfb.devicesManager.selectedSpeaker.activeEndpoint = .loudspeaker
            sfb.alertDelegate = self
            
        }

And energy impact goes extramely high ,And some extra log is always show in my console:
<img width="1114" alt="2017-02-08 9 54 55" src="https://cloud.githubusercontent.com/assets/23226451/22718471/f2017230-ede3-11e6-8cf8-874830786648.png">
This cause battery goes low fast even when i am not using Skype chat.
And this could be a problem.Because there is no way to unregistered the SfBApplication as long as i know.

P.S:I don't mean to be rude, but issues are leaving not answers for weeks or even months while demo is keeping on updating.I am curious about it.

**Comment by const86** [comment]
Energy impact during idle is expected to stay near zero. Quick test on iPhone 6s confirms that. When I join a meeting with audio, CPU consumption goes to 10% and Xcode says energy impact is 'Very High'. As soon as I leave the meeting, it's back to zero.
Some activity may happen even when idle. Normally it's like a couple HTTP requests in a minute, which doesn't cost much.
We may be measuring or interpreting results differently. The problem may be specific to your device or environment. More detailed reports on CPU and energy consumption could help to identify the source of the problem. Also please provide the full log of an idle run.

**Comment by 591700757** [comment]
@const86  Thanks for answering my questions.It seems i had been stupid and what you said is totally right.Energy impact goes to zero after i leave the meeting.Just Skype is always logging HTTP gives me the wrong vision that Skype is still running.Sorry for that.
