### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gourav7755** [OfficeDev/skype-ios-app-sdk-samples#42]
Hi,

We are using Skype IOS SDK. but its not woking fine every time it will show error  " The operation couldn't" be completed. (SfBErrorDomain error 570490883).

Please tell us this SDK is helpful or not

**Comment by AasveenKaur** [comment]
Please make sure that you download the latest SDK version and follow samples for better understanding. Also, make sure that you follow all the configuration steps mentioned in samples read me file.

**Comment by jovillas** [comment]
Closing ticket as we haven't heard back from OP in a while.
