### ISSUE TITLE
activeEndpoint null pointer(SDK1.1 issue)

### ISSUE THREAD

**Issue by 591700757** [OfficeDev/skype-ios-app-sdk-samples#46]
I tried to set activeEndpoint when i start app and set the other pamameter to sfb.configurationManager.But i found sometimes activeEndpoint is null and this crashes:

sfb.devicesManager.selectedSpeaker.activeEndpoint = .loudspeaker

So i give up set activeEndpoint when i start app instead i add observer and set .loudspeaker to activeEndpoint once Skype meeting connection is established.Which works fine before 1.1.
However random crash happens when i update to SDK 1.1 .
And the log says that crash happen at : 
    [self unsubscribeFrom:_speaker selector:@selector(activeEndpoint)];
in SfBConversationHelper.m 
I have no idea why this happens but this happen in 10% when i start my app and join meeting.
Hope you guys can show me a way to fix it.
Many thanks.

**Comment by 591700757** [comment]
I comment acitvieEndpoint addObserver in help.m since i don't use that observer i consider it OK.

**Comment by 591700757** [comment]
However i run through another round of test.And found activeEndpoint bad access still exist.
Which can be easily reproduce by the latest demo and SDK(1.1).

**Comment by tigerdyret** [comment]
This is still a major issue in 1.2. Please fix since it's a critical/blocker error.

**Comment by jovillas** [comment]
Thanks for reporting it.

We are tracking this issue on #61.
I'm closing this as duplicate to keep the conversation in one single place.
