### ISSUE TITLE
Text / Video chat is not getting initiated .

### ISSUE THREAD

**Issue by rahulganta2003** [OfficeDev/skype-ios-app-sdk-samples#47]
Hi Team ,

The app is built and launched correctly . We have provided an anonymous meeting url . When we are trying to invoke text / video chat we are getting an error in XCODE "ERROR APPLICATION CUcmpAnonMeetingJoinManager.cpp:75 empty meeting url" and an alert is shown with the below msg "The operation could not be completed .E_InvalidArgument(E0-0-3)" .
Could you please help us out in fixing this issue .

**Comment by AasveenKaur** [comment]
Hi Rahul,

Please download the latest Banking app sample and follow the read me file. We have a new settings page in the app. Please make sure that you configure these settings correctly based on your Skype for Business topology and enable preview feature. Anonymous meeting url can be entered in info.plist or at run time on settings page.

**Comment by jovillas** [comment]
Closing ticket as we haven't hear back from the OP in a while.

Please reopen if the problem persist.
