### ISSUE TITLE
Opening Skype for Business from App

### ISSUE THREAD

**Issue by jjb790** [OfficeDev/skype-ios-app-sdk-samples#52]
I'm trying to open an existing meeting url using the ms-sfb:// deep link URL. What is the correct format for specifying the meeting URL?
Example: 
let meetingURL = "https://meet.company.com/user/abcd1234"
let url = URL(string:"ms-sfb://chat?url=\(meetingURL)")
            if let _=url{
            UIApplication.shared.open(url!, options: [:], completionHandler: {success in
            })
}

It opens the Skype for Mobile app but does not join the specific chat link

**Comment by jovillas** [comment]
You can find documentation on URIs to start the SfB mobile client here: [Mobile URIs](https://msdn.microsoft.com/en-us/skype/skype-for-business-uris/sfbmobileuri)

The idea of the appSDK is that you can embed the SfB chat/video capabilities inside your own app, so you don't need to trigger SfB mobile client.
You can find more information about the AppSDK here: [Skype for Business App SDK](https://msdn.microsoft.com/en-us/skype/appsdk/skypeappsdk)

Does this answer the question?
