### ISSUE TITLE
Anonymous Meeting Join Problem

### ISSUE THREAD

**Issue by devwheel** [OfficeDev/skype-ios-app-sdk-samples#56]
New to IOS dev and loaded a Mac with all the new IDE's (xcode 8.3.2/Swift 3.1) 

loaded the project and a ton of changes (fix-its) were required.  Any chance to get a version of this part of the sdk-samples upgraded?

**Comment by jovillas** [comment]
A change was added to upgrade to Swift 3 few days ago [c6d91030967cfd835ce14d06d56d2fa0a7e830aa ](https://github.com/OfficeDev/skype-ios-app-sdk-samples/commit/c6d91030967cfd835ce14d06d56d2fa0a7e830aa)

Can you try this one? most of the the fix-it should be fixed now.
