### ISSUE TITLE
There are memory leaks in SkypeForBusiness.a

### ISSUE THREAD

**Issue by Dove0412** [OfficeDev/skype-ios-app-sdk-samples#57]
There are memory leaks in SkypeForBusiness.a .Often leads to a system crash.

**Comment by tigerdyret** [comment]
Any news on this? We are also having many stability issues due to the memory leak.

**Comment by krunalbhavsar** [comment]
Shameful for Microsoft. Not updating source code, with technology upgrade and not listening user complaints.

**Comment by const86** [comment]
One leak in the demo app is fixed. Two leaks are fixed in the framework, next release is coming soon.
