### ISSUE TITLE
Video doesn't show

### ISSUE THREAD

**Issue by jakepurple13** [OfficeDev/skype-ios-app-sdk-samples#58]
So its like this,

I'm trying to make an app that has a pure audio portion then you can click on a video camera icon and it takes you to a view where it shows video. But for some reasons its not showing the video. A lot of what I have is from the sdk example and it won't work. I have no idea why. I'm passing a conversation helper over/tried recreating it and both don't work. Any ideas?

**Comment by const86** [comment]
Do the SDK sample apps show video for you? If so, you might have missed starting video service. When using the helper, you should implement
```objc
- (void)conversationHelper:(SfBConversationHelper *)conversationHelper
              videoService:(SfBVideoService *)videoService
         didChangeCanStart:(BOOL)canStart;
```
and when `canStart` is `YES` do `[videoService start:&err]`.
