### ISSUE TITLE
Waiting for agent / How to "accept" conversation?

### ISSUE THREAD

**Issue by ralfr** [OfficeDev/skype-ios-app-sdk-samples#8]
We've worked through the getting started documentation, generate a Skype for Business meeting URL via the Skype for Business Web Scheduler and managed to get the iOS Banking Sample running on the simulator.

We've logged in another user via Lync for Mac, using the same meeting URL.

However, the app user is stuck at "Waiting for agent". There is no incoming request or anything like that on the Skype for Business Web App, where we've logged in another user.

Can you help clarify how this is supposed to work, please?

**Comment by ralfr** [comment]
Is it maybe, that a Skype for Business meeting created via the Web Scheduler does not allow anonymous participants?

**Comment by richardtaylorrt** [comment]
Hi - it could be.  Try following [these instructions](https://msdn.microsoft.com/en-us/skype/appsdk/getmeetingurl) (on a PC) for creating a meeting to use with the SDK.

One other possibility: are you using wifi or a mobile data network?  By default, the SDK doesn't permit video calls over a mobile network.  This can be changed: see the [API reference](https://ucwa.skype.com/appsdk/reference/iOS/Classes/SfBConfigurationManager.html#//api/name/requireWifiForVideo) for this.

Please let us know how you get on.

**Comment by ralfr** [comment]
Thanks for looking into this. It was in dead a problem with the configuration on the Skye for Business side. This can be marked as resolved.
